// <auto-generated />
using System;
using ApiEstudo.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ApiEstudo.Data.Migrations
{
    [DbContext(typeof(ApiEstudoContext))]
    partial class ApiEstudoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ApiEstudo.Domain.Entity.Geral.Casa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("AdminId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Casa", "Geral");
                });

            modelBuilder.Entity("ApiEstudo.Domain.Entity.Geral.Mensagem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("CasaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Texto")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CasaId");

                    b.ToTable("Mensagem", "Geral");
                });

            modelBuilder.Entity("ApiEstudo.Domain.Entity.Geral.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("bytea");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuario", "Geral");
                });

            modelBuilder.Entity("ApiEstudo.Domain.Entity.Geral.UsuarioCasa", b =>
                {
                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<long>("CasaId")
                        .HasColumnType("bigint");

                    b.HasKey("UsuarioId", "CasaId");

                    b.HasIndex("CasaId");

                    b.ToTable("Usuario_Casa", "Geral");
                });

            modelBuilder.Entity("ApiEstudo.Domain.Entity.Geral.Casa", b =>
                {
                    b.HasOne("ApiEstudo.Domain.Entity.Geral.Usuario", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("ApiEstudo.Domain.Entity.Geral.Mensagem", b =>
                {
                    b.HasOne("ApiEstudo.Domain.Entity.Geral.Casa", "Casa")
                        .WithMany("Mensagens")
                        .HasForeignKey("CasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Casa");
                });

            modelBuilder.Entity("ApiEstudo.Domain.Entity.Geral.UsuarioCasa", b =>
                {
                    b.HasOne("ApiEstudo.Domain.Entity.Geral.Casa", "Casa")
                        .WithMany("UsuarioCasas")
                        .HasForeignKey("CasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Casa");
                });

            modelBuilder.Entity("ApiEstudo.Domain.Entity.Geral.Casa", b =>
                {
                    b.Navigation("Mensagens");

                    b.Navigation("UsuarioCasas");
                });
#pragma warning restore 612, 618
        }
    }
}
